In [4]:
import numpy as np


In [5]:

np.random.seed(0)     #Random number generated remains the same across multiple runs
    
X= [[1, 2, 3, 2.5],                            #manually providing the input dataset   
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]


In [9]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


In [16]:
layer1 = Layer_Dense(4,2)           #defining the no. of inputs and no. of neurons of the layer1
layer2 = Layer_Dense(2,3)           #defining the no. of inputs and no. of neurons of the layer2

layer1.forward(X)                   #calculating the output of layer1
print(layer1.output)                  
layer2.forward(layer1.output)       #calculating the output of layer2 by using inputs as the output of layer1
print(layer2.output)

[[ -4.38550241 -10.33795322]
 [ -4.81772474  -4.36355877]
 [ -0.67810845  -1.67709835]]
[[ -3.28123419  14.67139537 -11.10833691]
 [ -3.23981842  10.9453994   -1.41241994]
 [ -0.5114607    2.32668871  -1.83889556]]
